version: '3.7'

services:

  liferaft:
    container_name: liferaft
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/liferaft'
      - '/liferaft/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true